<?php

/**
 * Baseepisodio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $titulo
 * @property string $descripcion
 * @property string $audio
 * @property integer $idPodcast
 * 
 * @method string   getTitulo()      Returns the current record's "titulo" value
 * @method string   getDescripcion() Returns the current record's "descripcion" value
 * @method string   getAudio()       Returns the current record's "audio" value
 * @method integer  getIdPodcast()   Returns the current record's "idPodcast" value
 * @method episodio setTitulo()      Sets the current record's "titulo" value
 * @method episodio setDescripcion() Sets the current record's "descripcion" value
 * @method episodio setAudio()       Sets the current record's "audio" value
 * @method episodio setIdPodcast()   Sets the current record's "idPodcast" value
 * 
 * @package    entrega3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseepisodio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('episodio');
        $this->hasColumn('titulo', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('descripcion', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('audio_ogg', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('audio_mp3', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));             
        $this->hasColumn('id_podcast', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}