<?php

/**
 * Basepodcast
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $descripcion
 * @property string $imagen
 * @property string $rss
 * @property boolean $habilitado
 * @property integer $idUsuario
 * @property integer $idCategoria
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $podcast_usuario
 * 
 * @method string              getNombre()          Returns the current record's "nombre" value
 * @method string              getDescripcion()     Returns the current record's "descripcion" value
 * @method string              getImagen()          Returns the current record's "imagen" value
 * @method string              getRss()             Returns the current record's "rss" value
 * @method boolean             getHabilitado()      Returns the current record's "habilitado" value
 * @method integer             getIdUsuario()       Returns the current record's "idUsuario" value
 * @method integer             getIdCategoria()     Returns the current record's "idCategoria" value
 * @method Doctrine_Collection getUsers()           Returns the current record's "Users" collection
 * @method Doctrine_Collection getPodcastUsuario()  Returns the current record's "podcast_usuario" collection
 * @method podcast             setNombre()          Sets the current record's "nombre" value
 * @method podcast             setDescripcion()     Sets the current record's "descripcion" value
 * @method podcast             setImagen()          Sets the current record's "imagen" value
 * @method podcast             setRss()             Sets the current record's "rss" value
 * @method podcast             setHabilitado()      Sets the current record's "habilitado" value
 * @method podcast             setIdUsuario()       Sets the current record's "idUsuario" value
 * @method podcast             setIdCategoria()     Sets the current record's "idCategoria" value
 * @method podcast             setUsers()           Sets the current record's "Users" collection
 * @method podcast             setPodcastUsuario()  Sets the current record's "podcast_usuario" collection
 * 
 * @package    entrega3
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basepodcast extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('podcast');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('descripcion', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('imagen', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('rss', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('habilitado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('idUsuario', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('idCategoria', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser as Users', array(
             'refClass' => 'podcast_usuario',
             'local' => 'podcast_id',
             'foreign' => 'usuario_id'));

        $this->hasMany('podcast_usuario', array(
             'local' => 'id',
             'foreign' => 'podcast_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}