categoria:
  class: sfDoctrineRouteCollection
  options:
    model:                categoria
    module:               categoria
    prefix_path:          /categoria
    column:               id
    with_wildcard_routes: true

podcast_usuario:
  class: sfDoctrineRouteCollection
  options:
    model:                podcast_usuario
    module:               podcast_usuario
    prefix_path:          /podcast_usuario
    column:               Array
    with_wildcard_routes: true

tipopodcast:
  class: sfDoctrineRouteCollection
  options:
    model:                tipopodcast
    module:               tipopodcast
    prefix_path:          /tipopodcast
    column:               id
    with_wildcard_routes: true

episodio:
  class: sfDoctrineRouteCollection
  options:
    model:                episodio
    module:               episodio
    prefix_path:          /episodio
    column:               id
    with_wildcard_routes: true

configuracion:
  class: sfDoctrineRouteCollection
  options:
    model:                configuracion
    module:               configuracion
    prefix_path:          /configuracion
    column:               id
    with_wildcard_routes: true

usuario:
  class: sfDoctrineRouteCollection
  options:
    model:                usuario
    module:               usuario
    prefix_path:          /usuario
    column:               id
    with_wildcard_routes: true

podcast:
  class: sfDoctrineRouteCollection
  options:
    model:                podcast
    module:               podcast
    prefix_path:          /podcast
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: podcast, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*


  
  
  
  
  