<?php

/**
 * categoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class categoriaTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object categoriaTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('categoria');
    }

    public static function getCategorias() {
        $q = self::getInstance()->createQuery('c')
                        ->select('id, nombre')
                        ->execute();
        return $q;
    }

    public static function getNombreCategoria($id) {
        $q = self::getInstance()->createQuery('c')
                        ->select('nombre')
                        ->where('c.id = ?', $id)
                        ->execute();
        return $q;
    }

}