<?php

/**
 * configuracionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class configuracionTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object configuracionTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('configuracion');
    }

    public static function getCantItemsBackEnd() {
        $sitio = self::getInstance()->find(1);
        $i = $sitio->getcantitemsbackend();
        return $i;
    }

    public static function getCantItemsFrontEnd() {
        $sitio = self::getInstance()->find(1);
        $i = $sitio->getcantitemsfrontend();
        return $i;
    }

    public static function getSiteName() {
        $configuracion = self::getInstance()->find(1);
        $name = $configuracion->gettitulo();
        return $name;
    }

    public static function getMensajeError() {
        $configuracion = self::getInstance()->find(1);
        $name = $configuracion->getmensajeerror();
        return $name;
    }

    public static function getHabilitado() {
        $configuracion = self::getInstance()->find(1);
        return $configuracion->gethabilitado();
    }

    public static function getEstilo() {
        $configuracion = self::getInstance()->find(1);
        return $configuracion->getestilo();
    }

    public static function getEstiloNombre() {
        $configuracion = self::getInstance()->find(1);
        if ($configuracion->getestilo() == 1)
            $estilo = "Default";
        else
            $estilo= "Other Style";
        return $estilo;
    }

}