<?php

/**
 * episodioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class episodioTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object episodioTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('episodio');
    }

    public static function getEpisodios($id) {
        $q = self::getInstance()->createQuery('e')
                        ->where('e.id_podcast = ?', $id)
                        ->execute();
        return $q;
    }

}