<?php

/**
 * podcast_usuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class podcast_usuarioTable extends Pluginpodcast_usuarioTable {

    /**
     * Returns an instance of this class.
     *
     * @return object podcast_usuarioTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('podcast_usuario');
    }

    public static function getSeguidores($idUsuario, $idPodcast) {

        $q = self::getInstance()->createQuery('pu')
                        ->where('pu.usuario_id = ?', $idUsuario)
                        ->andWhere('pu.podcast_id = ?', $idPodcast)
                        ->execute();
        if (count($q) > 0)
            return true;
        return false;
    }

    public static function getMisPodcast($idUsuario) {

        $q = self::getInstance()->createQuery('pu')
                        ->where('pu.usuario_id = ?', $idUsuario)
                        ->execute();
        return $q;
    }

}