generator:
  class: sfDoctrineGenerator
  param:
    model_class:           categoria
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          categoria
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        created_at: { label: Creado }
      title:   ~
      filter:
        display: [nombre]
      form:    ~
      edit:
        title: Editar categoria
      new:
        title: Crear categoria
      list:
        title: Lista de categorias
        display: [nombre, created_at]