<?php

/**
 * Pluginpodcast_usuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Pluginpodcast_usuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Pluginpodcast_usuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pluginpodcast_usuario');
    }
}